services:
  db:
    image: postgres:16
    container_name: writerly-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=writerly
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: writerly-languagetool
    ports:
      - "8010:8010"

volumes:
  pgdata:


